In [34]:
import numpy as np
import csv
import pymysql


config={
    'user':'root', #nome do Usuário do Banco
    'host':'localhost', #nome do Host do Banco
    'password':'[YFVe9BZ8zhi', #senha do Banco
    'database':'test_py'#nome do banco de dados
}

In [35]:
cnx = pymysql.connect(**config, charset='utf8')
cursor = cnx.cursor()
 
input_file = csv.DictReader(open("C:\\datasets\\BA.csv", encoding='utf-8'), delimiter=';')


In [36]:
for row in input_file:
    data_vacinacao = row['vacina_dataAplicacao']
    data_formatada =  data_vacinacao[0:10]
    data_formatada =  data_formatada.replace("-", "/")
    cursor.execute("INSERT INTO test_py.vacinacao(Data, PacienteID, Idade) VALUES (%s, %s, %s)",
                   (data_formatada,row['paciente_id'],row['paciente_idade']))
    cnx.commit()
   

ProgrammingError: (1146, "Table 'test_py.vacinacao' doesn't exist")

In [39]:
x=0
for row in input_file:
    data_vacinacao = row['vacina_dataAplicacao']
    data_formatada =  data_vacinacao[0:10]
    data_formatada =  data_formatada.replace("-", "/")
    print(data_formatada, row['paciente_dataNascimento'], row['estabelecimento_municipio_nome'], row['estabelecimento_uf'], row['vacina_descricao_dose'] )
    x += 1
    if (x>5):
        break
        
    
    
    

2021/02/06 10/06/1931 CAMACARI BA     1ª Dose
2021/03/18 09/08/1950 LAGOA REAL BA     1ª Dose
2021/02/28 01/03/1983 SALVADOR BA     1ª Dose
2021/03/17 12/12/1945 ITORORO BA     1ª Dose
2021/02/02 20/03/1927 ANDARAI BA     1ª Dose
2021/03/10 16/02/1942 FEIRA DE SANTANA BA     1ª Dose


In [16]:
print (input_file.fieldnames)


['document_id;paciente_id;paciente_idade;paciente_dataNascimento;paciente_enumSexoBiologico;paciente_racaCor_codigo;paciente_racaCor_valor;paciente_endereco_coIbgeMunicipio;paciente_endereco_coPais;paciente_endereco_nmMunicipio;paciente_endereco_nmPais;paciente_endereco_uf;paciente_endereco_cep;paciente_nacionalidade_enumNacionalidade;estabelecimento_valor;estabelecimento_razaoSocial;estalecimento_noFantasia;estabelecimento_municipio_codigo;estabelecimento_municipio_nome;estabelecimento_uf;vacina_grupoAtendimento_codigo;vacina_grupoAtendimento_nome;vacina_categoria_codigo;vacina_categoria_nome;vacina_lote;vacina_fabricante_nome;vacina_fabricante_referencia;vacina_dataAplicacao;vacina_descricao_dose;vacina_codigo;vacina_nome;sistema_origem;data_importacao_rnds']


In [10]:
val1, val2, val3 = np.loadtxt('dados.txt', skiprows=1, unpack=True)
print(val1)
print(val2)
print(val3)

[ 0.1212  0.104   0.5661  0.762 ]
[ 0.842     0.5422    0.932     0.847361]
[ 0.3672   0.34551  0.2344   0.1538 ]


In [13]:
my_array = np.genfromtxt('dados2.txt', skip_header=1, filling_values=-999)
print(my_array)

[[  1.21200000e-01   8.42000000e-01   3.67200000e-01]
 [ -9.99000000e+02   5.42200000e-01   3.45510000e-01]
 [  5.66100000e-01   9.32000000e-01  -9.99000000e+02]
 [  7.62000000e-01   8.47361000e-01   1.53800000e-01]]
