In [2]:
import numpy as np

l=[20, 30, 10, 40]
a = np.array(l)



In [3]:
print(a)

[20 30 10 40]


In [8]:
print(a[1:3])
print(a[::2])
print(a[:3])

[30 10]
[20 10]
[20 30 10]


In [11]:
b = np.array(l)
print(a)
print(b)
b[0]=1000
print(a)
print(b)


[20 30 10 40]
[20 30 10 40]
[20 30 10 40]
[1000   30   10   40]


In [12]:
b = a[:]
print(a)
print(b)
b[0]=1000
print(a)
print(b)

[20 30 10 40]
[20 30 10 40]
[1000   30   10   40]
[1000   30   10   40]


In [13]:
c= a.copy()
print(a)
print(c)
c[0] = 3000
print(a)
print(c)


[1000   30   10   40]
[1000   30   10   40]
[1000   30   10   40]
[3000   30   10   40]
